### ISSUE TITLE
Setting inital camera (cam) rotation

### ISSUE THREAD

**Issue by Eldainorn** [IceCreamYou/Nemesis#1]
Hello,

first I would like to thank you for this amazing piece of work. It really helps a lot trying to learn a few new things about first person controls.

What I have a problem with (and I am not sure why, since I never had any problems like this) is how can I set initial camera rotation? All is well except that I would like to rotate camera for 90° to the left when the game starts.

What I tried is after "raising camera of the ground"
`cam.position.y = UNITSIZE * .2;`

I tried to set rotation via the cam.rotation property. And it seems that nothing works unfortunately.

Otherwise everything is good so far.

Is there a simple solution for this?

Regards,
Eldainorn

**Comment by IceCreamYou** [comment]
Try setting e.g. `cam.rotation.y = 90` in your browser console while the game is running. If it works - and it does for me - then your problem is that the rotation is getting changed at some point after you set it, and you should track down where that's happening.

**Comment by Eldainorn** [comment]
Well, didn't work for me, but then I tried changing controls (FirstPersonControls) properties (mainly longitude) and it worked.

I made some adjustments and it seems I broke something. ^^

Thanks!
